export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  isVeg: boolean;
  isPopular?: boolean;
  image: string;
  category: string;
}

export const menuCategories = [
  "Soups",
  "Sandwiches & Light Bites",
  "Quick Bites",
  "Pasta",
  "Rice & Noodles",
  "Beverages",
];

export const menuItems: MenuItem[] = [
  // Soups
  {
    id: "soup-manchow-veg",
    name: "Veg Manchow Soup",
    description: "Classic Chinese soup with vegetables, crispy noodles & sesame oil",
    price: 90,
    isVeg: true,
    image: "/assets/food/manchow.jpg",
    category: "Soups",
  },
  {
    id: "soup-sweet-corn",
    name: "Sweet Corn Soup",
    description: "Creamy sweet corn broth with vegetables & herbs",
    price: 80,
    isVeg: true,
    image: "/assets/food/manchow.jpg",
    category: "Soups",
  },
  {
    id: "soup-chicken-manchow",
    name: "Chicken Manchow Soup",
    description: "Rich chicken broth with mushrooms, spring onions & fried noodles",
    price: 110,
    isVeg: false,
    isPopular: true,
    image: "/assets/food/manchow.jpg",
    category: "Soups",
  },
  {
    id: "soup-tomato",
    name: "Tomato Soup",
    description: "Fresh tomato blend with cream, herbs & garlic croutons",
    price: 75,
    isVeg: true,
    image: "/assets/food/manchow.jpg",
    category: "Soups",
  },

  // Sandwiches & Light Bites
  {
    id: "sandwich-cheese-garlic",
    name: "Cheese Garlic Sandwich",
    description: "Grilled sandwich with melted cheese, garlic butter & herbs",
    price: 110,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/cheese-garlic-sandwich.jpg",
    category: "Sandwiches & Light Bites",
  },
  {
    id: "sandwich-veg-grilled",
    name: "Veg Grilled Sandwich",
    description: "Multi-layered grilled veggies with mint chutney & cheese",
    price: 95,
    isVeg: true,
    image: "/assets/food/cheese-garlic-sandwich.jpg",
    category: "Sandwiches & Light Bites",
  },
  {
    id: "sandwich-chicken-club",
    name: "Chicken Club Sandwich",
    description: "Triple-decker with grilled chicken, lettuce, tomato & mayo",
    price: 140,
    isVeg: false,
    image: "/assets/food/cheese-garlic-sandwich.jpg",
    category: "Sandwiches & Light Bites",
  },
  {
    id: "maggie-veg-cheese",
    name: "Veg Cheese Maggie",
    description: "Jugnu-style loaded Maggie with cheese & secret masala",
    price: 100,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/veg-cheese-maggie.jpg",
    category: "Sandwiches & Light Bites",
  },

  // Quick Bites
  {
    id: "fries-peri-peri",
    name: "Peri Peri Fries",
    description: "Crispy golden fries tossed in our signature peri peri spice blend",
    price: 99,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/peri-peri-fries.jpg",
    category: "Quick Bites",
  },
  {
    id: "fries-loaded",
    name: "Loaded Cheese Fries",
    description: "Crispy fries loaded with melted cheese, jalapeños & sauces",
    price: 130,
    isVeg: true,
    image: "/assets/food/fries.jpeg",
    category: "Quick Bites",
  },
  {
    id: "bites-chilli-paneer",
    name: "Chilli Paneer",
    description: "Soft paneer cubes tossed in spicy Indo-Chinese sauce",
    price: 160,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/chilli-paneer.jpg",
    category: "Quick Bites",
  },
  {
    id: "bites-chicken-65",
    name: "Chicken 65",
    description: "Deep-fried spicy chicken bites with curry leaf tadka",
    price: 180,
    isVeg: false,
    isPopular: true,
    image: "/assets/food/chicken65.jpg",
    category: "Quick Bites",
  },
  {
    id: "bites-chicken-lollipop",
    name: "Chicken Lollipop",
    description: "Classic chicken lollipops in spicy tangy marinade",
    price: 200,
    isVeg: false,
    image: "/assets/food/chicken-lollipop.jpg",
    category: "Quick Bites",
  },
  {
    id: "bites-chilli-chicken",
    name: "Chilli Chicken",
    description: "Tender chicken in bold Indo-Chinese chilli sauce",
    price: 190,
    isVeg: false,
    isPopular: true,
    image: "/assets/food/chilli-chicken.jpeg",
    category: "Quick Bites",
  },

  // Pasta
  {
    id: "pasta-white-sauce",
    name: "White Sauce Pasta",
    description: "Creamy béchamel pasta with herbs, cheese & garlic",
    price: 149,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/white-sauce-pasta.jpg",
    category: "Pasta",
  },
  {
    id: "pasta-red-sauce",
    name: "Red Sauce Pasta",
    description: "Tangy tomato arrabbiata sauce with veggies & basil",
    price: 140,
    isVeg: true,
    image: "/assets/food/pasta.jpeg",
    category: "Pasta",
  },
  {
    id: "pasta-pink-sauce",
    name: "Pink Sauce Pasta",
    description: "A perfect blend of red & white sauce with mixed veggies",
    price: 160,
    isVeg: true,
    image: "/assets/food/pasta.jpeg",
    category: "Pasta",
  },
  {
    id: "pasta-chicken-white",
    name: "Chicken White Sauce Pasta",
    description: "Creamy white sauce pasta with grilled chicken pieces",
    price: 179,
    isVeg: false,
    image: "/assets/food/white-sauce-pasta.jpg",
    category: "Pasta",
  },

  // Rice & Noodles
  {
    id: "biryani-chicken",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice cooked with spiced chicken & saffron",
    price: 210,
    isVeg: false,
    isPopular: true,
    image: "/assets/food/biryani.jpg",
    category: "Rice & Noodles",
  },
  {
    id: "rice-veg-fried",
    name: "Veg Fried Rice",
    description: "Wok-tossed rice with vegetables, soy & aromatic spices",
    price: 120,
    isVeg: true,
    image: "/assets/food/fried-rice.jpeg",
    category: "Rice & Noodles",
  },
  {
    id: "rice-chicken-fried",
    name: "Chicken Fried Rice",
    description: "Classic fried rice with chicken, eggs & spring onions",
    price: 150,
    isVeg: false,
    image: "/assets/food/fried-rice.jpeg",
    category: "Rice & Noodles",
  },
  {
    id: "noodles-hakka-veg",
    name: "Veg Hakka Noodles",
    description: "Stir-fried noodles with colourful veggies & sesame sauce",
    price: 120,
    isVeg: true,
    image: "/assets/food/hakka-noodles.jpg",
    category: "Rice & Noodles",
  },
  {
    id: "noodles-hakka-chicken",
    name: "Chicken Hakka Noodles",
    description: "Stir-fried noodles with chicken strips in soy garlic sauce",
    price: 150,
    isVeg: false,
    isPopular: true,
    image: "/assets/food/hakka-noodles.jpg",
    category: "Rice & Noodles",
  },

  // Beverages
  {
    id: "bev-cold-coffee",
    name: "Cold Coffee",
    description: "Chilled blended coffee with milk, sugar & ice cream",
    price: 99,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/cold-coffee.jpg",
    category: "Beverages",
  },
  {
    id: "bev-oreo-shake",
    name: "Oreo Shake",
    description: "Thick creamy milkshake blended with Oreo cookies & vanilla",
    price: 120,
    isVeg: true,
    image: "/assets/food/oreo-shake.jpg",
    category: "Beverages",
  },
  {
    id: "bev-mojito",
    name: "Virgin Mojito",
    description: "Refreshing mint lime drink with sparkling soda & sugar syrup",
    price: 90,
    isVeg: true,
    isPopular: true,
    image: "/assets/food/mojito.jpeg",
    category: "Beverages",
  },
  {
    id: "bev-blue-lagoon",
    name: "Blue Lagoon Mocktail",
    description: "Exotic blue curacao flavoured mocktail with citrus splash",
    price: 110,
    isVeg: true,
    image: "/assets/food/blue-lagoon.jpg",
    category: "Beverages",
  },
  {
    id: "bev-masala-cola",
    name: "Masala Cold Drink",
    description: "Spiced fizzy drink with chaat masala, lemon & mint",
    price: 60,
    isVeg: true,
    image: "/assets/food/masala-coldrink.jpeg",
    category: "Beverages",
  },
];
